### ISSUE TITLE
Missing Class

### ISSUE THREAD

**Issue by sdianurag** [adonixis/android-sumbit-credit-card-flow#3]
Hello,
nice project. 
I was trying to use this cardflow in my project, and try to read the code but unable to find this
      
        `ru.adonixis.submitcreditcardflow.databinding.ActivitySubmitCreditCardBinding`

please help me to find this. 

Thanks.

**Comment by adonixis** [comment]
Hi,
class ActivitySubmitCreditCardBinding is not my own class, it's auto-generated class from the layout file "activity_submit_credit_card.xml" using the Android Data Binding Library. You can learn more here https://developer.android.com/topic/libraries/data-binding/index.html

**Comment by fxo140130** [comment]
adonix,

So how it is auto-generated? Can you elaborate? 

thanks
