### ISSUE TITLE
did't find     ActivitySubmitCreditCardBinding Class 

### ISSUE THREAD

**Issue by goswamiji0** [adonixis/android-sumbit-credit-card-flow#4]
Hi Thanks for this awasm example.
i am facing a problem that i am not able to get ActivitySubmitCreditCardBinding class where i found it

**Comment by adonixis** [comment]
Hi,
class ActivitySubmitCreditCardBinding is not my own class, it's auto-generated class from the layout file "activity_submit_credit_card.xml" using the Android Data Binding Library. You can learn more here https://developer.android.com/topic/libraries/data-binding/index.html
